#ifndef SWA_TOKENTYPESTRING
#define SWA_TOKENTYPESTRING
#include "tokentype.h"

#include <string>
std::string tokenTypeString(TokenType type) {
  switch (type) {
  case TokenType::LET:
    return "LET";
  case TokenType::CONST:
    return "CONST";
  case TokenType::OR:
    return "OR";
  case TokenType::AND:
    return "AND";
  case TokenType::IF:
    return "IF";
  case TokenType::ELSE:
    return "ELSE";
  case TokenType::WHILE:
    return "WHILE";
  case TokenType::INT:
    return "INT";
  case TokenType::INT64:
    return "INT64";
  case TokenType::FLOAT:
    return "FLOAT";
  case TokenType::STRING:
    return "STRING";
  case TokenType::BOOL:
    return "BOOL";
  case TokenType::BYTE:
    return "BYTE";
  case TokenType::STRUCT:
    return "STRUCT";
  case TokenType::PRINT:
    return "PRINT";
  case TokenType::FUNCTION:
    return "FUNCTION";
  case TokenType::MAIN:
    return "MAIN";
  case TokenType::RETURN:
    return "RETURN";
  case TokenType::TRUE:
    return "TRUE";
  case TokenType::FALSE:
    return "FALSE";
  case TokenType::IDENTIFIER:
    return "IDENTIFIER";
  case TokenType::NUMBER:
    return "NUMBER";
  case TokenType::CHARACTER:
    return "CHARACTER";
  case TokenType::ASSIGNMENT:
    return "ASSIGNMENT";
  case TokenType::COLON:
    return "COLON";
  case TokenType::COMMA:
    return "COMMA";
  case TokenType::DOT:
    return "DOT";
  case TokenType::SEMICOLON:
    return "SEMICOLON";
  case TokenType::QUESTION_MARK:
    return "QUESTION_MARK";
  case TokenType::TILDE:
    return "TILDE";
  case TokenType::OPEN_CURLY:
    return "OPEN_CURLY";
  case TokenType::CLOSE_CURLY:
    return "CLOSE_CURLY";
  case TokenType::OPEN_PAREN:
    return "OPEN_PAREN";
  case TokenType::CLOSE_PAREN:
    return "CLOSE_PAREN";
  case TokenType::OPEN_BRACKET:
    return "OPEN_BRACKET";
  case TokenType::CLOSE_BRACKET:
    return "CLOSE_BRACKET";
  case TokenType::EQUALS:
    return "EQUALS";
  case TokenType::NOT_EQUALS:
    return "NOT_EQUALS";
  case TokenType::GREATER_THAN:
    return "GREATER_THAN";
  case TokenType::GREATER_THAN_EQUALS:
    return "GREATER_THAN_EQUALS";
  case TokenType::LESS_THAN:
    return "LESS_THAN";
  case TokenType::LESS_THAN_EQUALS:
    return "LESS_THAN_EQUALS";
  case TokenType::PLUS:
    return "PLUS";
  case TokenType::PLUS_EQUALS:
    return "PLUS_EQUALS";
  case TokenType::MINUS:
    return "MINUS";
  case TokenType::MINUS_EQUALS:
    return "MINUS_EQUALS";
  case TokenType::MULTIPLY:
    return "MULTIPLY";
  case TokenType::STAR_EQUALS:
    return "STAR_EQUALS";
  case TokenType::DIVIDE:
    return "DIVIDE";
  case TokenType::MODULO:
    return "MODULO";
  case TokenType::DOUBLE_STAR:
    return "DOUBLE_STAR";
  case TokenType::AMPERSAND:
    return "AMPERSAND";
  case TokenType::VARIADIC:
    return "VARIADIC";
  case TokenType::DIALECT:
    return "DIALECT";
  case TokenType::ZERO:
    return "ZERO";
  case TokenType::WHITESPACE:
    return "WHITESPACE";
  case TokenType::COMMENT:
    return "COMMENT";
  case TokenType::NEWLINE:
    return "NEWLINE";
  case TokenType::ERROR:
    return "ERROR";
  case TokenType::END_OF_FILE:
    return "EOF";
  case TokenType::NOT:
    return "NOT";
  case TokenType::UNKNOWN:
  default:
    return "UNKNOWN";
  }
}

#endif // !SWA_TOKENTYPE
